name: Sync Moodle Tags

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch: # Allows manually triggering

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Moodle tags
        id: get-moodle-tags
        run: |
          MOODLE_TAGS=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/moodle/moodle/tags" | jq -r '.[].name')
          echo "moodle_tags<<EOF" >> $GITHUB_ENV
          echo "$MOODLE_TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get existing tags
        id: get-existing-tags
        run: |
          git fetch --tags
          EXISTING_TAGS=$(git tag -l)
          echo "existing_tags<<EOF" >> $GITHUB_ENV
          echo "$EXISTING_TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Process missing tags
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Convert existing tags to a pattern for quick matching
          EXISTING_TAGS_PATTERN=" ${{ env.existing_tags }} "
          
          # Process each Moodle tag
          for tag in ${{ env.moodle_tags }}; do
            # Only process version tags starting with 'v'
            if [[ ! "$tag" =~ ^v ]]; then
              continue
            fi
            
            # Check if tag exists
            if [[ "$EXISTING_TAGS_PATTERN" == *" $tag "* ]]; then
              echo "Tag $tag already exists, skipping"
              continue
            fi
            
            echo "Creating new tag: $tag"
            
            # Create and push tag
            git tag "$tag"
            git push origin "$tag"
            
            # Wait briefly to ensure tag is available
            sleep 2
            
            # Trigger build workflow ON THE TAG (using correct ref format)
            echo "Triggering build for tag $tag"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GH_PAT" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
              -d '{
                "ref": "refs/tags/'"$tag"'",  # <-- Formato correcto como en tu versión anterior
                "inputs": {
                  "moodle_version": "'"$tag"'"
                }
              }'
            
            # Small delay to avoid rate limiting
            sleep 3
          done
