name: Sync Moodle Tags

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch: # Allows manually triggering

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Moodle tags
        id: get-moodle-tags
        run: |
          MOODLE_TAGS=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/moodle/moodle/tags" | jq -r '.[].name')
          echo "moodle_tags<<EOF" >> $GITHUB_ENV
          echo "$MOODLE_TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get existing tags
        id: get-existing-tags
        run: |
          git fetch --tags
          EXISTING_TAGS=$(git tag -l)
          echo "existing_tags<<EOF" >> $GITHUB_ENV
          echo "$EXISTING_TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Process missing tags
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          IFS=$'\n' read -r -a moodle_tags <<< "${{ env.moodle_tags }}"
          IFS=$'\n' read -r -a existing_tags <<< "${{ env.existing_tags }}"
          
          for tag in "${moodle_tags[@]}"; do
            # Validate tag format: allow vX.Y.Z with optional suffix
            if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+)?$ ]]; then
              tag_exists=false
              for existing in "${existing_tags[@]}"; do
                if [ "$existing" == "$tag" ]; then
                  tag_exists=true
                  break
                fi
              done
              
              if [ "$tag_exists" = false ]; then
                echo "Creating tag: $tag"
                
                # Create and push tag
                git tag "$tag"
                git push origin "$tag"
                
                # Trigger build workflow
                curl -X POST \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Authorization: token $GH_PAT" \
                  https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
                  -d '{
                    "ref": "main",
                    "inputs": {
                      "moodle_version": "'"$tag"'"
                    }
                  }'
              fi
            else
              echo "Skipping tag (invalid format): $tag"
            fi
          done
